baseURL = 'https://scotreads.com/'
languageCode = 'en-us'
title = 'Scot Reads'

theme = "bookblog"

enableRobotsTXT = true


[menus]
    [[menus.main]]
    name = 'Reviews'
    pageRef = '/reviews'
    weight = 10

    [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 1